### ISSUE TITLE
Option to not wrap tab titles

### ISSUE THREAD

**Issue by maeveynot** [maciekmm/container-tabs-sidebar#18]
I'd like to be able to set tab titles to ellipsize instead of overflow. I can do this by hacking the CSS and temporarily loading a local copy of the extension, but if you're planning on adding an options page, that would be a preferable solution. I changed the style of `.container-tab-title` to include:

    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;

And this looks like what I want.

If you don't have your own plans to add an options page, would you accept a PR? I see other people have asked for things like color themes so it may be useful.

**Comment by nmorey** [comment]
+1

**Comment by nmorey** [comment]
I think you put the option the wrong way around.
When checking "wrap titles" in the options, titles are not wrapped and vice versa. But it works great thanks :)
