### ISSUE TITLE
Configurable tab groups

### ISSUE THREAD

**Issue by ouroborus** [maciekmm/container-tabs-sidebar#22]
I'd like to be able to disable, add, or remove the tab groups. (By default they appear as: Default, Personal, Work, Banking, Shopping)

**Comment by ouroborus** [comment]
Nevermind, I found the spot for that option. Need better (any) instructions instead.

**Comment by alexkalderimis** [comment]
@ouroborus - can you perhaps leave a hint as to what the solution was?

**Comment by ouroborus** [comment]
This is tied to a built-in Firefox feature, "Container Tabs", found under Settings > General > Tabs > Enable Container Tabs. You can't disable the feature and use this Add-on, but you can remove the various containers and they'll stop showing in the Add-on.
