### ISSUE TITLE
Open closed tab option

### ISSUE THREAD

**Issue by maciekmm** [maciekmm/container-tabs-sidebar#44]
The goal is to implement the feature "Undo closed tab" as an option in the tab and container context menu. 
I think that a global 'undo closed tab' is enough, no need to remember which tab was closed last in every container. Therefore (I think) the best place to add the logic is https://github.com/maciekmm/container-tabs-sidebar/blob/master/src/sidebar/native_context_menu.js

API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/getRecentlyClosed
adding a permission to manifest.json might be needed.

**Comment by AdavizeTheFirst** [comment]
> _No description provided._

Please could you provide a detailed description of this issue?

**Comment by maciekmm** [comment]
> > _No description provided._
> 
> Please could you provide a detailed description of this issue?

I updated the issue description. Thanks.

**Comment by chenxeed** [comment]
Thank you @maciekmm , let me have a look.

**Comment by maciekmm** [comment]
@chenxeed @AdavizeTheFirst are any of You working on it? :)
