### ISSUE TITLE
Configuration of containers is not obvious

### ISSUE THREAD

**Issue by matkoch** [maciekmm/container-tabs-sidebar#46]
I was digging through some closed issues here, before I've found that the configuration is in the normal "Preferences | General" page.

**Comment by maciekmm** [comment]
I agree, what would you recommend?

**Comment by elfi** [comment]
I'd put it under about:addons instead of the current about:preferences.
It's really difficult to find there, mostly because the mindset is: "I want to configure a plugin, not the Firefox itself".

**Comment by maciekmm** [comment]
@elfi While a good point I don't want to reimplement the whole UI to add/remove containers. It's already there and also in Multi-Account containers addons. Having it in this addon seems like an unnecessary redundancy. I can add a note saying that containers can be configured in about:preferences.
What do you think?

**Comment by elfi** [comment]
@maciekmm , yes, a note would be great. I'd think the best location for such a note, a hyperlink?, would be at about:addons / Container Tabs Sidebar / Preferences tab .

**Comment by maciekmm** [comment]
@elfi
A hyperlink is unfortunately not permitted due to firefox security policies. But I have added the note, thanks.
