### ISSUE TITLE
Focus on tab in the same container after closing current tab

### ISSUE THREAD

**Issue by maximbaz** [maciekmm/container-tabs-sidebar#56]
Right now when I close the tab, a "random" tab gets focused next ("random" if you judge by looking at sidebar alone).

What would be really cool is to be able to focus a tab in the same container if possible.

I would suggest this algorithm:

- If tab just above the currently closed one is in the same container, focus it
- Otherwise, if tab just below the currently closed one is in the same container, focus it
- Otherwise, if there is tab above, focus it
- Otherwise, focus tab below

**Comment by maciekmm** [comment]
@maximbaz 
Hello, thanks for the feature request.
The current algorithm is the default one of the firefox and focuses the last active card (or at least it should).
I could think about focusing the last one in the container, but the one suggested by you would be confusing. What do you think?

**Comment by maximbaz** [comment]
That could work too I guess - it's just that I removed the standard horizontal tab bar, I only have vertical sidebar, and when I close tabs I get very confused where the focus goes... So I thought focusing it somewhere close would be intuitive, and simpler to implement 😄 But yes, at least let's not jump between containers 👍

**Comment by maciekmm** [comment]
@maximbaz 
I implemented your initial suggestion, but it has to be activated in addon's options. It will however focus the tab above, as while testing I found it frustrating the other way around. Though your mileage may vary, so I might add more customization to this. The feature will appear in the next release, but can be tested now if you build the addon from source.
