### ISSUE TITLE
Tabs switching in view-order

### ISSUE THREAD

**Issue by zemiret** [maciekmm/container-tabs-sidebar#57]
It would be nice to be able to choose to switch tabs (with Ctrl+Tab) in order in which they're visible, not in the order they were opened in.

**Comment by maciekmm** [comment]
Taking a quick look at documentation I found no API to change the behavior. Without some wild hackery (activating tabs one by one while having "recently used order" option turned on) I see no way to change this behavior other than injecting custom javascript and capturing ctrl+tab while on page.

However, as mentioned, you can change the behavior to "recently used" by switching appropriate setting in "about:preferences".

**Comment by MiniGod** [comment]
In the Firefox Multi-Account Containers addon, there's a "Sort Tabs" button. After sorting the tabs, Ctrl+Tab works as expected. I've been using that as a work around.

A quick search, it looks like this is the implementation:
https://github.com/mozilla/multi-account-containers/blob/d654810d417ca54818e24fc3897d0d6ca7aa57d0/src/js/background/backgroundLogic.js#L240-L287

**Comment by maciekmm** [comment]
@MiniGod Thank you for the reference. Will see whether this can be incorporated ;)

**Comment by maciekmm** [comment]
Fixed as of 0.3.4.
The feature is currently opt-in.
