### ISSUE TITLE
Collapsing behaviour

### ISSUE THREAD

**Issue by clemera** [maciekmm/container-tabs-sidebar#59]
Thanks for this nice extension it really works well!

One issue I have is that when selecting a pinned tab, the container view collapses. This also happens when opening a new tab. As I hide the regular tab bar and want to navigate only with the side view this is annoying when you want to check a pinned tab for example and then want to go back to tab you came from by clicking on it.

**Comment by maciekmm** [comment]
Hello @clemera 
Go to `about:addons`, click the ContainerTabsSidebar addon and go to preferences and make sure "Collapse containers" option is left unchecked.
![image](https://user-images.githubusercontent.com/3267517/80397089-ede6b780-88b5-11ea-861c-f487f9043e64.png)

Thank you for the report.

**Comment by clemera** [comment]
Oops, sorry I could swear I had checked that but apparently I did miss the save button. Thank you!

**Comment by clemera** [comment]
If I may quickly ask another question: Do you know of a way to open new tabs in the current container? I couldn't find any preference to configure that.

**Comment by clemera** [comment]
I found the following extension which does this: https://addons.mozilla.org/en-US/firefox/addon/sticky-containers/
