### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by maciekmm** [maciekmm/container-tabs-sidebar#6]
- [x] collapse trees on tab change
- [ ] custom CSS
- [ ] show tabs from all windows
- [ ] only show tabs from the currently focused container in tab bar
- [x] theming support
- [ ] merged containers prefix (interop with temporary containers addon)
- [x] customizable shortcut
- [x] configurable text ellipsis

**Comment by storyjesse** [comment]
+1 for collapse trees on tab change. I see that it's possible to add custom CSS to firefox through userChrome.css does this mean it's possible to make trees collapsed by default? It seems that whenever a new tab is selected all collapsed trees are expanded. Being able to choose the opposite would be enough for me, but ideally it would be better to remember all trees collapse/expanded state so that it doesn't change when switching between tabs.

**Comment by storyjesse** [comment]
I've found the style.css and it looks like I can achieve what I want by just editing this file. However, no changes I make have any effect. I've looked around for an explanation of how to use style.css in a plugin but not found one. Can someone tell me how to make the edited .mozilla/firefox/272asd89.default/container-tabs-sidebar-0.0.3/style.css be reloaded? Restarting firefox doesn't work.

**Comment by storyjesse** [comment]
I've found that if I type into the location bar: "about:debugging#addons" I can find a link to the Manifest URL which on my system is; `moz-extension://d74b57eb-1bfa-43b4-a4fc-b8a7d9eb586f/manifest.json`
and contains:
`{
    "manifest_version": 2,
    "name": "Container Tabs Sidebar",
    **"version": "0.0.4",**
    "description": "Container sidebar tab management",
    "homepage_url": "https://github.com/maciekmm/container-tabs-sidebar",
    "sidebar_action": {
      "default_title": "Container Tabs",
      "default_panel": "sidebar/sidebar.html",
      "default_icon": "assets/sidebar-icon.svg",
      "browser_style": true
    },
    "browser_action": {
      "default_icon": "assets/sidebar-icon.svg",
      "default_title": "Open ContainerTabsSidebar"
    },
    "background": {
      "scripts": ["action_button.js"]
    },
    "commands": {
      "_execute_sidebar_action": {
        "suggested_key": {
          "default": "F2"
        },
        "description": "show sidebar"
      }
    },
    "applications": {
      "gecko": {
        "id": "containertabssidebar@maciekmm.net",
        "strict_min_version": "54.0a2"
      }
    },
    "icons": {
      "98": "assets/icon98.png"
    },
    "permissions": [
      "tabs",
      "contextualIdentities",
      "cookies"
    ]
}
`
Note the version number 0.0.4 the css file I've been editing is under ../container-tabs-sidebar-**0.0.3** !!

So I'm editing the wrong file. But how do I find the correct one? I've being using GNU find and grep for the past hour but haven't found any other instances of the plugin. How do I find the location of this manifest.json file above?
Any help would be greatly appreciated.
cheers

**Comment by storyjesse** [comment]
I think I might have found it!

> /home/jesse/.mozilla/firefox/272yp8i6.default/extensions/containertabssidebar@maciekmm.net.xpi

This file contains a fair bit of binary but enough text for me to see that it is version 0.0.4
Am I right in thinking that this xpi file is a compilation of the source code?
This would mean that to edit the style.css file I would need to download the latest source from here on github and make some changes then somehow compile it into an xpi and install that in firefox.

**Comment by storyjesse** [comment]
Oh wow, I just put containertabssidebar@maciekmm.net.xpi through GNU less and what do you know, less could read it!! and tells me it's an archive containing the 19 source files!! :-D

```
 Archive:  /home/jesse/.mozilla/firefox/272yp8i6.default/extensions/containertabssidebar@maciekmm.net.xpi
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    4218  Defl:N     3364  20% 2018-07-27 23:25 a274347f  META-INF/mozilla.rsa
       0  Stored        0   0% 2018-07-28 01:22 00000000  assets/
       0  Stored        0   0% 2018-07-28 01:22 00000000  sidebar/
       0  Stored        0   0% 2018-07-28 01:22 00000000  sidebar/containers/
     663  Defl:N      357  46% 2018-07-28 01:22 79d8f3a7  action_button.js
    1069  Defl:N      424  60% 2018-07-28 01:22 8670dc40  manifest.json
     596  Defl:N      581   3% 2018-07-28 01:22 190d4d16  assets/icon98.png
    3693  Defl:N     1830  50% 2018-07-28 01:22 0b61a7ab  assets/no-favicon.svg
     897  Defl:N      382  57% 2018-07-28 01:22 c7e95e13  assets/sidebar-icon.svg
    2883  Defl:N      826  71% 2018-07-28 01:22 3608b3e2  sidebar/context_menu.js
     736  Defl:N      253  66% 2018-07-28 01:22 789becca  sidebar/sidebar.html
    3246  Defl:N     1032  68% 2018-07-28 01:22 dbf4d6f3  sidebar/sidebar.js
    3740  Defl:N     1065  72% 2018-07-28 01:22 ba5b10a4  sidebar/style.css
    9990  Defl:N     2212  78% 2018-07-28 01:22 2134fe9a  sidebar/tab.js
    3788  Defl:N      973  74% 2018-07-28 01:22 7998850f  sidebar/containers/container.js
    8078  Defl:N     1823  77% 2018-07-28 01:22 07625b79  sidebar/containers/contextual.js
    2120  Defl:N      659  69% 2018-07-28 01:22 92b5cce9  sidebar/containers/pinned.js
    2662  Defl:N     1219  54% 2018-07-27 23:25 83bc5ea3  META-INF/manifest.mf
     190  Defl:N      153  20% 2018-07-27 23:25 874c4fbf  META-INF/mozilla.sf
--------          -------  ---                            -------
   48569            17153  65%                            19 files

```

I'm on the right track :-D

**Comment by maciekmm** [comment]
Hi @storyjesse,
I am currently a bit busy, have you achieved what you wanted? ;)

**Comment by storyjesse** [comment]
No I got busy too. I got as far as packaging up my altered code into an .xpi but I'm doing something wrong and it wouldn't install. I haven't got time to learn right now but if you know of a good tutorial you could link me to that would be awesome. I'll read it when I again have spare time. ;-)
