### ISSUE TITLE
Container selection with horizontal bar

### ISSUE THREAD

**Issue by clemera** [maciekmm/container-tabs-sidebar#61]
I have a feature suggestion which I think could give a really neat interface: 

I use one pinned tab per container and would like to omit the tree view and instead show only the container tabs of the selected pinned tab.  Or if you don't want to mix the two, an option to add a horizontal container selection bar like the pinned tab bar. Using pinned tabs as indicators has the advantage of showing site favicons which makes it easier to distinguish the containers.

What do you think about that?

**Comment by maciekmm** [comment]
If i understood You correctly, you would like to instead of displaying the container header, display the pinned tabs associated with the container?

**Comment by clemera** [comment]
That was my intention yes. But I already switched to Tab center reborn which more or less works more that way. Still you extension was great to use, thank you for your work!

**Comment by maciekmm** [comment]
@clemera 
Good to hear there are solutions to suit Your needs.

Will close this now :)
