### ISSUE TITLE
Make Free Space in Pane Draggable

### ISSUE THREAD

**Issue by Nonameentered** [maciekmm/container-tabs-sidebar#62]
I'd like to be able to drag my window around using the free space below all my tabs (or even using the header/container labels). I tried just adding `-moz-window-dragging: drag;` to root, but that doesn't seem to work. Is this possible to implement (either in the extension or through CSS customization)?

**Comment by maciekmm** [comment]
I don't understand what you try to achieve.
What do you mean by dragging windows around?
Do you want to grab the empty space from one window to another to have them merged?

**Comment by Nonameentered** [comment]
I’d like to click on the empty space below all my tabs and be able to use this space to do something like drag the window to one side of the screen.

**Comment by maciekmm** [comment]
Would you like for the empty space to act like a title bar? Where you can move the whole browser window?

I don't think it's possible, if you've seen such a thing before please let me know. :)

**Comment by Nonameentered** [comment]
Yes that’s exactly what I’m hoping for. I know it’s possible to add “draggable space” on the address bar that lets you do this, and if I’m not mistaken the empty space next to tabs on the top tab bar would work for this if I hadn’t hidden it.
If I remember correctly, Tree Style Tabs might do this, but I’ll check back later and let you know!

**Comment by Nonameentered** [comment]
Update: Looks like I was wrong. Tree Style Tabs doesn't do this. After some more googling you seem right that there doesn't seem like an easy way to make this work, so I'll close this for now!
