### ISSUE TITLE
Proposal: shortcuts to open new tab

### ISSUE THREAD

**Issue by onsails** [maciekmm/container-tabs-sidebar#63]
It would be much more productive to open new tabs using just keyboard without need to aim "plus" button.

I propose emacs/vim-like keyboard-chod prefix to select a container for a new tab. For example to open a tab in "Work" container user should press `Ctrl-Q + w`. For Banking `Ctrl-Q + B`. To make it more obvious for user which key to press the character should be underlined in a sidebar. For example:

_P_ersonal
_W_ork
_B_anking
_S_hopping
B_l_ockchain

Note the B_l_ockchain item. It underlines `l` because there is already a Banking container, and in lexicographic order it's before Blockchain. That's why Banking "wins" usage of the first character Blockchain gets the second.

Also a shortcut to open new tab in container of the current tab would be neat.

**Comment by maciekmm** [comment]
Although a nice idea I don't think the feature should be included in this add-ons.
CTS aims to be purely visual. Other add-ons might help you with tab management.
