### ISSUE TITLE
Unclear Shortcut Format

### ISSUE THREAD

**Issue by gbrindisi** [maciekmm/container-tabs-sidebar#64]
Hi!
great extension!

In the preference panel what's the format for the configurable shortcut?
In particular what should I put if I want to have `Ctrl+X` or even `⌘X` if I am on OSX?

**Comment by gbrindisi** [comment]
I suppose this is related: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations ?

**Comment by maciekmm** [comment]
@gbrindisi Yes, this is exactly what you are looking for :)
Have you managed to figure this out?
Command+X should work on OSX

**Comment by gbrindisi** [comment]
Yes, with that guideline it works.
I suggest to add a brief description in the preference panel to make it
more obvious :)

**Comment by maciekmm** [comment]
@gbrindisi Will do, thanks for the report!
