### ISSUE TITLE
Group tmp tab groups

### ISSUE THREAD

**Issue by marchenm** [maciekmm/container-tabs-sidebar#65]
When using the [temp-containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/?src=search) extension, it'd be nice to group all "tmp" containers into one group even though they aren't in one group

**Comment by maciekmm** [comment]
Thank you for the request :rocket: 
Will prioritize this feature now as there seems to be a high demand for it.

Will close in favor of #24
