### ISSUE TITLE
Allow nesting of tabs like TreeStyleTabs

### ISSUE THREAD

**Issue by aksrikanth** [maciekmm/container-tabs-sidebar#66]
Tabs that open in a different container can be top level.

This is particularly helpful when I'm searching for things online -- I can open a bunch of child tabs that have results and sort through them later (or collapse the children if I want to ignore them).

**Comment by maciekmm** [comment]
Hello @aksrikanth,
thank you for the feature request.

After some consideration I concluded that the feature does not fit the project's objective. I don't see a reason for categorizing by both container and folder.

You could try submitting a feature request to TreeStyleTabs to make containers default tree root elements.
