### ISSUE TITLE
Change container names

### ISSUE THREAD

**Issue by hypexr** [maciekmm/container-tabs-sidebar#70]
I can't figure out how to change the container names. Am I missing something in the configuration?

**Comment by MiniGod** [comment]
Containers are native in Firefox.

You can edit them in the preferences: about:preferences#containers

**Comment by maciekmm** [comment]
There's many people reporting inability to find container configuration. We might think about adding configuration UI to addon's options, but I am a bit reluctant to doing so as it would duplicate the logic in firefox preferences.
