### ISSUE TITLE
Separate permanent containers from temporary containers group

### ISSUE THREAD

**Issue by Zebrazilla** [maciekmm/container-tabs-sidebar#71]
Since support for temporary containers have been added (#24), which was a great addition btw., I've noted that all containers created by the temporary containers add-on will get grouped as temporary containers, even permanent containers.

In the temporary containers add-on there is the possibility of converting a temporary container to a permanent container, such a permanent container I think should be separated and not grouped under temporary containers in the sidebar.

**Comment by Zebrazilla** [comment]
Clarification: Permanent containers do appear separate from temporary containers but only after a restart.

**Comment by maciekmm** [comment]
Thank You for the report, fixed as of 0.3.3
