### ISSUE TITLE
"Default" container does not expand when creating new tab (ctrl+t)

### ISSUE THREAD

**Issue by MiniGod** [maciekmm/container-tabs-sidebar#75]
When creating a new tab with Ctrl+t, it opens in the "Default" container.
If the "Default" tab list is collapsed, the active tab (new tab) is hidden inside the collapsed "Default" list.

Switching tabs expands the list, but not when creating a new tab.

**Comment by maciekmm** [comment]
Thank you for the report, fixed as of 0.3.4
