### ISSUE TITLE
Tabs Galore Using Duplicate, Move to Container, and Move to New Window

### ISSUE THREAD

**Issue by matty1086** [maciekmm/container-tabs-sidebar#80]
Hi,
I'm not sure when this started, but it's been ongoing for a while. 

When using the move tab to new window functionality, the tab moves to a new window, however, it also opens up 8 additional blank tabs - each in their own window.

When using the duplicate tab functionality, it duplicates - 10 times.

When using the reopen in container functionality, it reopens in the new container - 9 additional times.

Below is a recording of all 3 behaviors:
https://i.imgur.com/VDUUdfG.mp4

Happy to provide any additional details.

Expected behavior:
Move to new window: The tab moves to a new window. 1 new window opens.
Duplicate tab: The tab is duplicated once
Reopen in container: The tab is opened in the new container once

Firefox Version: 77.0.1
Plugin Version: 0.3.4

**Comment by maciekmm** [comment]
Thank You for the report. It looks like some behavior changed in the context menu APIs. It should be fixed in 0.3.5.
