### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by khawajamechatronics** [maciekmm/container-tabs-sidebar#82]
Hi,

I hope you are doing well. Your extension is very user friendly. I request a feature to be added which I think will make a lot of difference is

Adding Custom Markers.

This feature is in Tab Side Add On
https://addons.mozilla.org/en-US/firefox/addon/tab-sidebar-we/

But its not easy to use in that app.

Let me know if you have any questions.

Thanks

**Comment by maciekmm** [comment]
Thanks for the request.

Could you please elaborate on what a custom marker is and how does it improve your workflow?

**Comment by khawajamechatronics** [comment]
Custom Marker are a Marker/Tab, in your scenario its a container Name Show in the list.

We can hide tabs in certain container so list get shrinks. In development world its called folding.

So in case of long list of tabs, tabs will be arranged according to container assigned and can fold a specific container or list so the list doesn't occupy space when not in use.

Let me know if I had explained well.

**Comment by khawajamechatronics** [comment]
I see you already have folding in containers. Let me make it simple, I actually Like all the features you already have, Only thing I don't want is multi account feature. 
I don't want to separate account on separate container.  My Use case is use same account for all container. Is it possible. Also I dont like 'reopen' to new container. I wish to use 'Move' option. In My scenario I will have same account shared in all containers.

**Comment by khawajamechatronics** [comment]
https://github.com/mozilla/multi-account-containers/issues/1820

I also raised same request on Mozilla Container Repo

**Comment by maciekmm** [comment]
@khawajamechatronics The whole purpose of Multi account container (MAC) is to have separate cookie containers and isolation, hence the name "multi-account". Container Tabs Sidebar (CTS) groups tabs visually to better represent that isolation and do so vertically.

You may want to look at [TreeStyleTab](https://github.com/piroor/treestyletab) where you can define "folders" or just use [Tab Sidebarhttps://addons.mozilla.org/en-US/firefox/addon/tab-sidebar-we/) if it suits your needs.

This feature does neither belong to CTS nor MAC I'm afraid.

**Comment by khawajamechatronics** [comment]
I have tried Tree Style Tab. Its not user friendly. Dozen of option and really hard to understand function changes.

Tab Sidebar is good option I am currently using that. But your implementation is very very useful, productive and easy to manage. I understand your addon is based on mozilla Containers but if it was done without multi account feature then it will be very useful for users like me.

I hope sooner or later you will see opportunity in this.

Best Regards.

**Comment by Solid-Ice8** [comment]
@khawajamechatronics 

Have you tried Simple Tabs Group?
