### ISSUE TITLE
Fence Icon Broken on Container Tabs

### ISSUE THREAD

**Issue by benyaminl** [maciekmm/container-tabs-sidebar#89]
Hello, I'm a new user of Container Tabs. I tried to set one of my container with fence icon, but either the icon is broken or the Icon won't show at all. 

Seems the fence icon is broken. I don't know why. I seen the icon is available on the Repo. It's strage indeed. 
https://github.com/maciekmm/container-tabs-sidebar/blob/master/src/assets/contextual-identities/fence.svg

Broken Fence
![image](https://user-images.githubusercontent.com/2817332/109376884-0a9ab400-78fa-11eb-9792-740a75827a69.png)
![image](https://user-images.githubusercontent.com/2817332/109376903-1ab29380-78fa-11eb-8c7b-f81d6859820e.png)

Working with other icon 
![image](https://user-images.githubusercontent.com/2817332/109376906-269e5580-78fa-11eb-8bc5-4c86a587c8f5.png)
![image](https://user-images.githubusercontent.com/2817332/109376907-2bfba000-78fa-11eb-97dd-6dac83dff05d.png)

Only Fence Icon that's broken.

**Comment by maciekmm** [comment]
Hello,
I fixed the issue, but didn't release an update on addons portal, doing it now.

Thanks.

**Comment by benyaminl** [comment]
Related to https://github.com/maciekmm/container-tabs-sidebar/issues/84 
Thanks
