### ISSUE TITLE
Firefox Find Bar close button is hidden

### ISSUE THREAD

**Issue by WildSnail913** [maciekmm/container-tabs-sidebar#99]
When the Container Tabs Sidebar is open, the Firefox ctrl+f Find Bar's close button that appears in the right corner is hidden.

The close button reappears when the Container tabs Sidebar is closed.

Browser: Firefox 92.0 (64-bit)

Made the window tiny for the screenshot but seems to happen regardless of window size.

![sidebar](https://user-images.githubusercontent.com/83524145/134092534-df561b8f-9416-487f-89fd-d457869586ff.png)

**Comment by maciekmm** [comment]
Hello @WildSnail913, thanks for reporting the issue, but it looks like this happens with any sidebar in general and thus looks like a bug in Firefox itself, not Container Tabs Sidebar. Could you please report it in the Firefox bugtracker? https://bugzilla.mozilla.org/home
